//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class inventorydbEntities : DbContext
{
    public inventorydbEntities()
        : base("name=inventorydbEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<edited_mat> edited_mat { get; set; }
    public virtual DbSet<material> materials { get; set; }
    public virtual DbSet<user> users { get; set; }
    public virtual DbSet<color> colors { get; set; }
}
